### ISSUE TITLE
Retours TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp3-2016-2017-groupe-1-paccaud_roussel#1]
Le code est pas mal

⚠️ Le tableau dans le rapport c'est pas génial pour moi

**Comment by MrPingouin1** [comment]
Bonjour,
Je ne comprends pas pourquoi le tableau ne fonctionne pas sur GitHub alors qu'il fonctionne sur d'autre lecteur de fichier MD tel que : http://dillinger.io/ 

Comment puis-je faire?

**Comment by Slashgear** [comment]
Je fais confiance à la doc officiel de github https://guides.github.com/features/mastering-markdown/

**Comment by MrPingouin1** [comment]
Merci, du coup j'ai pris la syntaxe de Git et cela marche plutôt bien. 
En revanche le texte ne sera pas centré dans les case comme nous l'avions souhaité mais ce n'est pas très grave.

**Comment by Slashgear** [comment]
👍
